apiVersion: v1
kind: Secret
metadata:
  name: dynamic-dns-config
type: Opaque
data:
  email: eW91QGV4YW1wbGUuY29t
  username: dXNlcm5hbWUK
  password: cGFzc3dvcmQ=
  requestURL: aHR0cHM6Ly9kb21haW5zLmdvb2dsZS5jb20vbmljL3VwZGF0ZQ==
  hostname: c3ViZG9tYWluLmV4YW1wbGUuY29t
